SzkolaXXII/SzkolaXXII/Controllers/AdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using SzkolaXXII.Common.Security.Roles;
using SzkolaXXII.Web.Areas.Identity.Data;
using SzkolaXXII.Web.Data;
using SzkolaXXII.Web.InputModel;
using SzkolaXXII.Web.Models.School;
using SzkolaXXII.Web.ViewModel;

namespace SzkolaXXII.Web.Controllers
{
    [Authorize(Roles = SystemDefaultRoles.Administrator)]
    public class AdminController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly SchoolContext _context;

        public AdminController(UserManager<User> userManager, SchoolContext usersContext)
        {
            _userManager = userManager;
            _context = usersContext;
        }

        public async Task<IActionResult> Index()
        {
            return RedirectToAction("Roles");
        }

        public async Task<IActionResult> Roles()
        {
            var model = new List<AdminUserRolesViewModel>();

            foreach (var user in _userManager.Users)
            {
                var roles = (await _userManager.GetRolesAsync(user)).ToList();

                model.Add(new AdminUserRolesViewModel
                {
                    UserId = user.Id,
                    Name = user.UserName,
                    Email = user.Email,
                    Schools = null,
                    Roles = roles
                });
            }

            return View(model);
        }

        public async Task<IActionResult> AddUserRole(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = _userManager.Users.FirstOrDefault(x => x.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            var allRoles = _context.Roles.Select(x => x.Name).ToList();
            var userRoles = (await _userManager.GetRolesAsync(user)).ToList();

            var schools = _context.Namespace.ToList();
            var schoolDictionary = new Dictionary<string, string>();

            schools.ForEach(x =>
            {
                schoolDictionary.Add(x.Name, x.Id);
            });

            var viewModel = new AdminUserRolesViewModel
            {
                UserId = id,
                Name = user.UserName,
                Email = user.Email,
                Roles = allRoles.Where(x => !userRoles.Contains(x)).ToList(),
                Schools = schoolDictionary
            };

            return View(new UserRoleInputModel
            {
                ViewModel = viewModel
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddUserRole(UserRoleInputModel model)
        {
            if (model.Role == null || model.ViewModel.UserId == null)
            {
                return NotFound("Wprowadzone dane są niepoprawne.");
            }

            var user = _userManager.Users.FirstOrDefault(x => x.Id == model.ViewModel.UserId);
            if (user == null)
            {
                return NotFound("Nie znaleziono takiego użytkownika.");
            }

            try
            {
                await _userManager.AddToRoleAsync(user, model.Role);
                await _userManager.UpdateAsync(user);

                await CreateSubTableDataForRole(user, model);

                return RedirectToAction("Roles");
            }
            catch (Exception ex)
            {
                return NotFound(ex.Message);
            }
        }

        public async Task<IActionResult> DeleteUserRole(string id)
        {
            var user = _userManager.Users.FirstOrDefault(x => x.Id == id);

            if (user == null)
            {
                return NotFound();
            }

            var roles = await _userManager.GetRolesAsync(user);

            if (roles.Count <= 0)
            {
                return NotFound("Brak ról przypisanych do użytkownika.");
            }

            var schoolId = string.Empty;

            if (roles.Contains(SystemDefaultRoles.Student))
            {
                schoolId = _context.SchoolStudent.FirstOrDefault(x => x.StudentId == user.Id)?.SchoolId;

            }
            else if (roles.Contains(SystemDefaultRoles.Teacher))
            {
                schoolId = _context.SchoolTeacher.FirstOrDefault(x => x.TeacherId == user.Id)?.SchoolId;
            }

            var schools = new Dictionary<string, string>();

            _context.Namespace
                .Where(x => x.Id == schoolId)
                .ToList()
                .ForEach(x => schools.Add(x.Name, x.Id));

            var model = new UserRoleInputModel
            {
                ViewModel = new AdminUserRolesViewModel
                {
                    UserId = user.Id,
                    Name = user.UserName,
                    Email = user.Email,
                    Roles = roles.ToList(),
                    Schools = schools
                },
                SchoolId = schoolId
            };

            ViewData["ErrorMessage"] = "";
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteUserRole(UserRoleInputModel model, string role)
        {
            if (string.IsNullOrEmpty(role) || model == null)
            {
                return NotFound();
            }

            if (_context.Roles.FirstOrDefault(x => x.Name == role) == null)
            {
                return NotFound();
            }

            var user = _userManager.Users.FirstOrDefault(x => x.Id == model.ViewModel.UserId);
            if (user == null)
            {
                return NotFound();
            }

            try
            {
                await _userManager.RemoveFromRoleAsync(user, role);
                await _userManager.UpdateAsync(user);

                await DeleteSubTableDataForUser(user, role, model.SchoolId);

                return RedirectToAction("Roles");
            }
            catch (Exception ex)
            {
                ViewData["ErrorMessage"] = $"Wystąpił nieoczekiwany błąd przy usuwaniu roli. Treść błędu: {ex.Message}";

                return View(model);
            }
        }

        private async Task CreateSubTableDataForRole(User user, UserRoleInputModel model)
        {
            var school = _context.Namespace.FirstOrDefault(x => x.Id == model.SchoolId);

            switch (model.Role)
            {
                case SystemDefaultRoles.Student:
                    SchoolStudent schoolStudent = new SchoolStudent
                    {
                        Id = Guid.NewGuid().ToString(),
                        School = school,
                        SchoolClass = null,
                        Student = user
                    };

                    _context.SchoolStudent.Add(schoolStudent);
                    break;

                case SystemDefaultRoles.Teacher:
                    SchoolTeacher schoolTeacher = new SchoolTeacher
                    {
                        Id = Guid.NewGuid().ToString(),
                        School = school,
                        SchoolClass = null,
                        Teacher = user
                    };

                    _context.SchoolTeacher.Add(schoolTeacher);
                    break;

                default:
                    return;
            }

            await _context.SaveChangesAsync();
        }

        private async Task DeleteSubTableDataForUser(User user, string role, string schoolId)
        {
            switch (role)
            {
                case SystemDefaultRoles.Student:
                    var schoolStudent = _context.SchoolStudent.FirstOrDefault(x => x.StudentId == user.Id && x.SchoolId == schoolId);

                    if (schoolStudent == null)
                    {
                        return;
                    }

                    _context.SchoolStudent.Remove(schoolStudent);
                    break;

                case SystemDefaultRoles.Teacher:
                    var schoolTeacher = _context.SchoolTeacher.FirstOrDefault(x => x.TeacherId == user.Id && x.SchoolId == schoolId);

                    if (schoolTeacher == null)
                    {
                        return;
                    }

                    _context.SchoolTeacher.Remove(schoolTeacher);
                    break;

                default:
                    return;
            }

            await _context.SaveChangesAsync();
        }
        public async Task<IActionResult> SchoolList()
        {
            return View(await _context.Namespace.ToListAsync());
        }
    }
}

SzkolaXXII/SzkolaXXII/Controllers/GradebookController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.Linq;
using SzkolaXXII.Web.Areas.Identity.Data;
using SzkolaXXII.Web.Data;
using SzkolaXXII.Web.Models.School;
using SzkolaXXII.Web.Policies;
using SzkolaXXII.Web.ViewModel;

namespace SzkolaXXII.Web.Controllers
{
    public class GradebookController : Controller
    {
        private readonly SchoolContext _context;
        private readonly UserManager<User> _userManager;

        public GradebookController(SchoolContext schoolContext, UserManager<User> userManager)
        {
            _context = schoolContext;
            _userManager = userManager;
        }

        [Authorize(Policy = AuthorizationPolicies.Name.AtLeastStudent)]
        public IActionResult Index(string namespaceId, string classId, string subjectId)
        {
            var userId = _userManager.GetUserId(User);
            var teachers = _context.SchoolTeacher.Where(x => x.TeacherId == userId);
            var students = _context.SchoolStudent.Where(x => x.StudentId == userId);
            var classes = new List<SchoolClass>();
            var schoolStudents = new List<StudentSelectModel>();
            var assignments = new List<Assignment>();

            if (string.IsNullOrEmpty(namespaceId))
            {
                if (teachers.Any())
                {
                    var namespaces = _context.Namespace.Where(x => teachers.Any(y => y.SchoolId == x.Id));

                    if (namespaces.Count() > 1)
                    {
                        ViewData["Schools"] = new SelectList(namespaces, "Id", "Name");
                    }
                    else
                    {
                        namespaceId = namespaces.FirstOrDefault()?.Id;
                    }
                }
                else if (students.Any())
                {
                    var namespaces = _context.Namespace.Where(x => students.Any(y => y.SchoolId == x.Id));

                    if (namespaces.Count() > 1)
                    {
                        ViewData["Schools"] = new SelectList(namespaces, "Id", "Name");
                    }
                    else
                    {
                        namespaceId = namespaces.FirstOrDefault()?.Id;
                    }
                }
                else
                {
                    return NotFound();
                }
            }

            if(teachers.Any())
            {
                classes = _context.SchoolClass.Where(x => students.Any(y => y.SchoolId == x.SchoolId)).ToList();
            }
            else
            {
                classes = _context.SchoolClass.Where(x => x.SchoolId == namespaceId).ToList();
            }


            if (!string.IsNullOrEmpty(classId))
            {
                if(students.Any(x => x.SchoolClassId != classId))
                {
                    return NotFound();
                }

                var schoolClass = _context.SchoolClass.FirstOrDefault(x => x.Id == classId);

                var subjectClasses = _context.SubjectSchoolClass
                    .Where(x => x.SchoolClassId == schoolClass.Id);

                if (!string.IsNullOrEmpty(subjectId))
                {
                    var subjectClass = subjectClasses.FirstOrDefault(x => x.SubjectId == subjectId);
                    if (subjectClass != null)
                    {
                        var subject = _context.Subject.FirstOrDefault(x => x.Id == subjectId);

                        assignments = _context.Assigment.Where(x => x.SubjectId == subjectId).ToList();

                        schoolStudents = GetStudentsModel(classId, assignments);

                        ViewData["SubjectName"] = subject == null ? "nie rozpoznano nazwy przedmiotu" : subject.Name;
                    }
                }

                var subjects = _context.Subject
                    .Where(x => subjectClasses.Any(y => y.SubjectId == x.Id))
                    .ToList();

                ViewData["Classes"] = new SelectList(classes, "Id", "Name", classes.FirstOrDefault(x => x.Id == classId));
                ViewData["Subjects"] = new SelectList(subjects, "Id", "Name", subjects.FirstOrDefault(x => x.Id == subjectId));
            }
            else
            {
                ViewData["Classes"] = new SelectList(classes, "Id", "Name");
            }

            var model = new GradebookViewModel
            {
                NamespaceId = namespaceId,
                ClassId = classId,
                SubjectId = subjectId,
                SchoolStudents = schoolStudents,
                Assignments = assignments
            };

            return View(model);
        }

        private List<StudentSelectModel> GetStudentsModel(string classId, List<Assignment> assignments)
        {
            var list = new List<StudentSelectModel>();

            var schoolClass = _context.SchoolClass.FirstOrDefault(x => x.Id == classId);
            var students = _context.SchoolStudent
                .Where(x => x.SchoolClassId == schoolClass.Id)
                .ToList();

            foreach (var student in students)
            {
                var grades = _context.SubjectGrade
                    .ToList()
                    .Where(x => x.StudentId == student.Id && assignments.Any(y => y.Id == x.SubjectId))
                    .ToList();

                list.Add(new StudentSelectModel
                {
                    Id = student.Id,
                    Email = _userManager.Users.FirstOrDefault(x => x.Id == student.StudentId)?.Email,
                    Grades = grades
                });
            }

            return list;
        }
    }
}

SzkolaXXII/SzkolaXXII/Controllers/NotesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using SzkolaXXII.Common.Security.Roles;
using SzkolaXXII.Web.Areas.Identity.Data;
using SzkolaXXII.Web.Data;
using SzkolaXXII.Web.Models.School;
using SzkolaXXII.Web.Policies;
using SzkolaXXII.Web.ViewModel;

namespace SzkolaXXII.Web.Controllers
{
    public class NotesController : Controller
    {
        private readonly SchoolContext _schoolContext;
        private readonly UserManager<User> _userManager;

        public NotesController(SchoolContext schoolContext, UserManager<User> userManager)
        {
            _schoolContext = schoolContext;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            var userId = _userManager.GetUserId(User);
            var notes = _schoolContext.Notes.Where(x => x.StudentId == userId);

            List<NotesViewModel> list = new List<NotesViewModel>();

            foreach (var item in notes)
            {
                list.Add(new NotesViewModel
                {
                    Notes = item,
                    User = _schoolContext.Users.FirstOrDefault(x => x.Id == item.TeacherId),
                    Color = item.Read ? "#C6C6C6" : "#FFFFF0"
                });
            }

            if (list.Count > 1) list.OrderBy(x => x.Notes.Time);

            return View(list);
        }

        public async Task<IActionResult> ShowNotes(string id)
        {
            var notes = _schoolContext.Notes.FirstOrDefault(x => x.Id == id);

            if (!notes.Read)
            {
                notes.Read = true;
                _schoolContext.Notes.Update(notes);

                await _schoolContext.SaveChangesAsync();
            }

            NotesViewModel notesViewModel = new NotesViewModel()
            {
                Notes = notes,
                User = _schoolContext.Users.FirstOrDefault(x => x.Id == notes.TeacherId),
            };

            return View(notesViewModel);
        }
    }
}

SzkolaXXII/SzkolaXXII/Views/Shared/_AdminMenuHeader.cshtml
<!DOCTYPE html>

<html lang="pl">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/light-bootstrap-dashboard.css" />
    <!--     Fonts and icons     -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
</head>
<body>
    <nav class="navbar navbar-expand-lg " color-on-scroll="500">
        <div class="container-fluid">
            <a class="navbar-brand" style="color:#A9A9A9"> Dashboard </a>
            <button href="" class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-bar burger-lines"></span>
                <span class="navbar-toggler-bar burger-lines"></span>
                <span class="navbar-toggler-bar burger-lines"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navigation">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                            <a class="material-icons" style="font-size:28px; margin-top:30px; color:#A9A9A9" asp-area="Identity" asp-page="/Account/Manage/Index">perm_identity</a>
                    </li>
                    <li class="nav-item">
                        <form id="logoutForm" class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                            <button id="logout" type="submit" style="border-color: #ffffff; font-size:15px; color:#808080" class="nav-link btn btn-link">Wyloguj</button>
                        </form>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</body>
</html>

SzkolaXXII/SzkolaXXII/Views/Shared/_AdminMenuPartial.cshtml
<!DOCTYPE html>

<html lang="pl">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/light-bootstrap-dashboard.css" />
    <!--     Fonts and icons     -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
</head>
<body>
    <div class="logo">
        <a asp-area="" asp-controller="Home" asp-action="Index" class="simple-text">
            SzkołaXXII
        </a>
    </div>
	<ul class="nav">
		<li class="nav-item">
			<a class="nav-link" asp-area="" asp-controller="Admin" asp-action="Roles">
				<i class="material-icons">build</i>
				<p>Role</p>
			</a>
		</li>
		<li>
			<a class="nav-link" asp-area="" asp-controller="Admin" asp-action="SchoolList">
				<i class="material-icons">school</i>
				<p>Szkoły</p>
			</a>
		</li>
		<li>
			<a class="nav-link" asp-area="" asp-controller="SchoolClasses" asp-action="Index">
				<i class="material-icons">people</i>
				<p>Klasy uczniów</p>
			</a>
		</li>
		<li>
			<a class="nav-link" asp-area="" asp-controller="SchoolTeachers" asp-action="Index">
				<i class="material-icons">people</i>
				<p>Nauczyciele</p>
			</a>
		</li>
	</ul>

</body>
</html>

SzkolaXXII/SzkolaXXII/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using SzkolaXXII.Common.Security.Roles
@inject SignInManager<SzkolaXXII.Web.Areas.Identity.Data.User> SignInManager
@inject UserManager<SzkolaXXII.Web.Areas.Identity.Data.User> UserManager
<!DOCTYPE html>

<html lang="pl">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>SzkolaXXII - @ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/login-register.css" />
    <!--     Fonts and icons     -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
</head>
<body class="index-page sidebar-collapse">
    <nav class="navbar navbar-expand-lg bg-primary fixed-top">
        <div class="container">
            <a class="navbar-translate" asp-area="" asp-controller="Home" asp-action="Index">SzkolaXXII</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse" id="example-navbar-primary">
                <partial name="_LoginPartial" />
                <ul class="navbar-nav flex-grow-1">
                    @if (SignInManager.IsSignedIn(User))
                    {
                        var user = await UserManager.GetUserAsync(User);
                        var roles = await UserManager.GetRolesAsync(user);

                        @if (roles.Contains(SystemDefaultRoles.Administrator))
                        {
                        }
                        else if (roles.Contains(SystemDefaultRoles.Moderator))
                        {
                            <li class="nav-item">
                                <a class="nav-link" style="margin-left:10px" asp-area="" asp-controller="SchoolClasses" asp-action="Index">Grupy zajęciowe</a>
                            </li>
                        }
                        else if (roles.Contains(SystemDefaultRoles.Teacher))
                        {
                            <li class="nav-item">
                                <a class="nav-link" style="margin-left:10px" asp-area="" asp-controller="Gradebook" asp-action="Index">Dziennik</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Timetable" asp-action="TeacherIndex">Plan lekcji</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="CalendarEvent" asp-action="Index">Kalendarz</a>
                            </li>
                        }
                        else if (roles.Contains(SystemDefaultRoles.Student))
                        {
                            <li class="nav-item">
                                <a class="nav-link" style="margin-left:10px" asp-area="" asp-controller="Gradebook" asp-action="Index">Dziennik</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Timetable" asp-action="Index">Plan lekcji</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="CalendarEvent" asp-action="Index">Kalendarz</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Subjects" asp-action="StudentSubject">Przedmioty</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Notes" asp-action="Index">Uwagi</a>
                            </li>
                        }
                    }
                </ul>
            </div>
        </div>
    </nav>
    <div class="wrapper" style="margin-top:100px; margin-bottom:100px">
        <div class="container">
            <div class="row">
                <main role="main" class="pb-3 col-md-11 px-4">
                    @RenderBody()
                </main>
            </div>
        </div>
        <footer class="footer fixed-bottom">
            <div class=" container ">
                <div class="text-center" id="copyright">
                    &copy; 2020 - SzkolaXXII - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                </div>
            </div>
        </footer>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

SzkolaXXII/SzkolaXXII/Views/Shared/_PanelLayout.cshtml
<!DOCTYPE html>

<html lang="pl">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>SzkolaXXII - Panel administratora - @ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/light-bootstrap-dashboard.css" />
    <!--     Fonts and icons     -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />
</head>
<body>
    <main>
        @RenderBody()
    </main>
    <footer class="border-top footer text-muted fixed-bottom">
        <div class="container text-center">
            &copy; 2020 - SzkolaXXII - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

SzkolaXXII/SzkolaXXII/Views/Shared/_TeacherMenuPartial.cshtml
<!DOCTYPE html>

<html lang="pl">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/light-bootstrap-dashboard.css" />
    <!--     Fonts and icons     -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
</head>
<body>
    <div class="logo">
        <a asp-area="" asp-controller="Home" asp-action="Index" class="simple-text">
            SzkołaXXII
        </a>
    </div>
    <ul class="nav">
        <li class="nav-item">
            <a class="nav-link" asp-area="" asp-controller="TeacherPanel" asp-action="Subjects">
                <i class="material-icons">book</i>
                <p>Kursy</p>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" asp-area="" asp-controller="TeacherPanel" asp-action="Notes">
                <i class="material-icons">comment</i>
                <p>Uwagi</p>
            </a>
        </li>
    </ul>
</body>
</html>

SzkolaXXII/SzkolaXXII/Views/Shared/_TeacherOneSubjectPartial.cshtml
<!DOCTYPE html>

<html lang="pl">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/light-bootstrap-dashboard.css" />
    <!--     Fonts and icons     -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
</head>
<body>
    <div class="logo">
        <a asp-area="" asp-controller="Home" asp-action="Index" class="simple-text">
            SzkołaXXII
        </a>
    </div>
    <ul class="nav">
        <li class="nav-item">
            <a class="nav-link" asp-area="" asp-action="Edit" asp-route-id="@ViewData["Id"]">
                <i class="material-icons">edit</i>
                <p>Edycja przedmiotu</p>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" asp-area="" asp-action="Class" asp-route-id="@ViewData["Id"]">
                <i class="material-icons">people</i>
                <p>Pokaż klasy</p>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" asp-area="" asp-action="Calendar" asp-route-subjectId="@ViewData["Id"]">
                <i class="material-icons">calendar_today</i>
                <p>Kalendarz</p>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" asp-area="" asp-action="Timetable" asp-route-subjectId="@ViewData["Id"]">
                <i class="material-icons">calendar_today</i>
                <p>Plan lekcji</p>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" asp-area="" asp-controller="TeacherPanel" asp-action="Index">
                <i class="material-icons">keyboard_arrow_left</i>
                <p>Powrót</p>
            </a>
        </li>
    </ul>
</body>
</html>