SzkolaXXII/SzkolaXXII/Models/School/Subject.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SzkolaXXII.Web.Models.School
{
    public class Subject
    {
        [Key]
        public string Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string SchoolId { get; set; }
        public string TeacherId { get; set; }
        public Namespace School { get; set; }
        public ICollection<Assignment> Assignments { get; set; }
        public ICollection<SubjectTeacher> SubjectTeacher { get; set; }
        public ICollection<SubjectSchoolClass> SubjectSchoolClass { get; set; }
    }
}

SzkolaXXII/SzkolaXXII/Controllers/SchoolClassesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using SzkolaXXII.Common.Security.Roles;
using SzkolaXXII.Web.Areas.Identity.Data;
using SzkolaXXII.Web.Data;
using SzkolaXXII.Web.Models.School;
using SzkolaXXII.Web.Policies;
using SzkolaXXII.Web.ViewModel;

namespace SzkolaXXII.Web.Controllers
{
    [Authorize(Policy = AuthorizationPolicies.Name.AtLeastTeacher)]
    public class SchoolClassesController : Controller
    {
        private readonly SchoolContext _context;
        private readonly UserManager<User> _userManager;

        public SchoolClassesController(SchoolContext context, UserManager<User> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(User);
            var roles = await _userManager.GetRolesAsync(user);


            if (roles.Contains(SystemDefaultRoles.Administrator))
            {
                ViewData["schoolCount"] = 2;
                ViewData["schools"] = _context.Namespace;
                var schoolClasses = await _context.SchoolClass.Include(s => s.Educator.Teacher).ToListAsync();
                return View(schoolClasses);
            }


            var schoolCount = _context.SchoolTeacher.Where(x => x.TeacherId == user.Id).Count();
            var schoolId = _context.SchoolTeacher.Where(x => x.TeacherId == user.Id).Select(x => x.SchoolId);
            ViewData["schoolCount"] = schoolCount;
            ViewData["schools"] = _context.Namespace.Where(x => schoolId.Contains(x.Id));
            var schoolContext = await _context.SchoolClass.Where(x => schoolId.Contains(x.SchoolId)).Include(s => s.Educator.Teacher).ToListAsync();

            return View(schoolContext);
        }

        public async Task<IActionResult> SchoolChosenIndex(string id)
        {
            ViewData["school"] = await _context.Namespace.FindAsync(id);
            var schoolContext = await _context.SchoolClass.Include(s => s.Educator.Teacher).Where(x => x.SchoolId == id).ToListAsync();
            return View(schoolContext);
        }

        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var schoolClass = await _context.SchoolClass
                .Include(s => s.Educator)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (schoolClass == null)
            {
                return NotFound();
            }

            return View(schoolClass);
        }

        [Authorize(Policy = AuthorizationPolicies.Name.AtLeastModerator)]
        public async Task<IActionResult> Create()
        {
            List<SelectListItem> listOfTeachers = (from st in _context.SchoolTeacher
                                                   where !(
                                                      from sc in _context.SchoolClass
                                                      select sc.EducatorId
                                                    ).Contains(st.Id)
                                                   select new SelectListItem { Text = st.Id, Value = st.Teacher.UserName }).ToList();
            ViewData["EducatorCount"] = _context.SchoolTeacher.Count();
            ViewData["EducatorId"] = new SelectList(listOfTeachers, "Text", "Value");
            ViewData["School"] = new SelectList(_context.Namespace, "Id", "Name");
            ViewData["SchoolsCount"] = _context.Namespace.Count();

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = AuthorizationPolicies.Name.AtLeastModerator)]
        public async Task<IActionResult> Create([Bind("Id,Name,StartSchoolDate,EndSchoolDate,EducatorId,SchoolId")] SchoolClass schoolClassInput)
        {
            if (ModelState.IsValid && !_context.SchoolClass.Any(e => e.EducatorId == schoolClassInput.EducatorId))
            {
                var schoolClass = new SchoolClass
                {
                    Id = Guid.NewGuid().ToString(),
                    Name = schoolClassInput.Name,
                    StartSchoolDate = schoolClassInput.StartSchoolDate,
                    EndSchoolDate = schoolClassInput.EndSchoolDate,
                    Educator = _context.SchoolTeacher.FirstOrDefault(x => x.Id == schoolClassInput.EducatorId),
                    EducatorId = schoolClassInput.EducatorId,
                    School = _context.Namespace.FirstOrDefault(x => x.Id == schoolClassInput.SchoolId),
                    SchoolId = schoolClassInput.SchoolId
                };

                _context.Add(schoolClass);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }

            var teachers = await _context.SchoolTeacher.Include(s => s.Teacher).ToListAsync();
            IEnumerable<SelectListItem> items = teachers.Select(teacher => new SelectListItem
            {
                Value = teacher.Id,
                Text = teacher.Teacher.Email
            });

            ViewData["EducatorCount"] = _context.SchoolTeacher.Count();
            ViewData["EducatorId"] = items;
            ViewData["SchoolsCount"] = _context.Namespace.Count();
            ViewData["School"] = new SelectList(_context.Namespace, "Id", "Name", schoolClassInput.SchoolId);

            return View(schoolClassInput);
        }

        [Authorize(Policy = AuthorizationPolicies.Name.AtLeastModerator)]
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var schoolClass = await _context.SchoolClass.FindAsync(id);
            if (schoolClass == null)
            {
                return NotFound();
            }

            var teachers = await _context.SchoolTeacher.Include(s => s.Teacher).ToListAsync();
            IEnumerable<SelectListItem> items = teachers.Select(teacher => new SelectListItem
            {
                Value = teacher.Id,
                Text = teacher.Teacher.Email
            });

            ViewData["EducatorsCount"] = await _context.SchoolTeacher.CountAsync();
            ViewData["EducatorId"] = items;

            return View(schoolClass);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = AuthorizationPolicies.Name.AtLeastModerator)]
        public async Task<IActionResult> Edit(string id, [Bind("Id,Name,StartSchoolDate,EndSchoolDate,EducatorId,SchoolId")] SchoolClass schoolClass)
        {
            if (id != schoolClass.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(schoolClass);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException ex)
                {
                    if (!SchoolClassExists(schoolClass.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw ex;
                    }
                }

                return RedirectToAction(nameof(Index));
            }

            var teachers = await _context.SchoolTeacher.Include(s => s.Teacher).ToListAsync();
            IEnumerable<SelectListItem> items = teachers.Select(teacher => new SelectListItem
            {
                Value = teacher.Id,
                Text = teacher.Teacher.Email
            });

            ViewData["EducatorsCount"] = await _context.SchoolTeacher.CountAsync();
            ViewData["EducatorId"] = items;
            return View(schoolClass);
        }

        [Authorize(Policy = AuthorizationPolicies.Name.AtLeastModerator)]
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var schoolClass = await _context.SchoolClass
                .Include(s => s.Educator.Teacher)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (schoolClass == null)
            {
                return NotFound();
            }
            return View(schoolClass);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = AuthorizationPolicies.Name.AtLeastModerator)]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var schoolClass = await _context.SchoolClass.FindAsync(id);

            _context.SchoolClass.Remove(schoolClass);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> ShowStudents(string id)
        {
            if (_context.SchoolStudent.Count() <= 0)
            {
                return View(new List<SchoolStudentIndexViewModel>());
            }

            var viewModel = new List<SchoolStudentIndexViewModel>();

            foreach (var student in _context.SchoolStudent)
            {
                if (student.SchoolClassId == id)
                {
                    viewModel.Add(new SchoolStudentIndexViewModel
                    {
                        StudentId = student.Id,
                        Student = await _userManager.FindByIdAsync(student.StudentId),
                        SchoolClass = _context.SchoolClass.FirstOrDefault(n => n.Id == student.SchoolClassId),
                        SchoolClassId = student.SchoolClassId
                    });

SzkolaXXII/SzkolaXXII/Views/Subjects/AddClass.cshtml
@model SzkolaXXII.Web.InputModel.AddClassInputModel
@{
    ViewData["Title"] = "AddClass";
}

<h1>Dodaj klase</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddClass">
            <input asp-for="Id" type="hidden" />
            <table class="table table-borderless table-responsive-md">
                @if (Model.List.Count > 0)
                {
                    <tbody>
                        <tr>
                            <td>Klasa</td>
                            <td><select class="form-control" asp-for="ClassId" asp-items="@Model.List.Select(x => new SelectListItem(x.Name, x.Id))"></select></td>
                        </tr>
                        <tr>
                            <td colspan="2">
                                <button type="submit" class="btn btn-primary">Dodaj</button>
                                <a class="ml-2" asp-action="Class" asp-route-id="@Model.Id">Powrót do listy</a>
                            </td>
                        </tr>
                    </tbody>
                }
                else
                {
                    <tbody>
                        <tr>
                            <td>Brak klas do dodania</td>                           
                        </tr>
                        <tr>
                            <td colspan="2">
                                <a class="ml-2" asp-action="Class" asp-route-id="@Model.Id">Powrót do listy</a>
                            </td>
                        </tr>
                    </tbody>
                }
            </table>
        </form>
    </div>
</div>

SzkolaXXII/SzkolaXXII/Views/Subjects/Class.cshtml
@model SzkolaXXII.Web.ViewModel.SubjectSchoolClassViewModel
@{
    ViewData["Title"] = "Klasy";
}

<p>
    <a asp-action="AddClass" asp-route-id="@Model.Id">Dodaj nową klase do przedmiotu</a>
</p>

<table class="table">
    <thead>
        @if (Model != null && Model.List.Count() > 0)
        {
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.List[0].Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.List[0].StartSchoolDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.List[0].EndSchoolDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.List[0].Educator)
                </th>
                <th></th>
            </tr>
        }
    </thead>
    <tbody>
        @if (Model != null)
            @foreach (var item in Model.List)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @item.StartSchoolDate.Date.ToString("MM/dd/yyyy")
                    </td>
                    <td>
                        @item.EndSchoolDate.Date.ToString("MM/dd/yyyy")
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Educator.Id)
                    </td>
                    <td>
                        <a asp-controller="SchoolClasses" asp-action="ShowStudents" asp-route-id="@item.Id">Pokaż Klase</a> |
                        <a asp-action="Remove" asp-route-SubjectId="@Model.Id" asp-route-ClassId="@item.Id">Usuń Klase Z Przedmiotu</a>
                    </td>
                </tr>
            }
    </tbody>
</table>
<div>
    <a asp-action="Details" asp-route-id="@Model.Id">Powrót do listy</a>
</div>

SzkolaXXII/SzkolaXXII/Views/Subjects/Create.cshtml
@model SzkolaXXII.Web.InputModel.SubjectInputModel

@{
    ViewData["Title"] = "Create";
}
@using SzkolaXXII.Web.Data;
@using Microsoft.AspNetCore.Identity;
@using SzkolaXXII.Common.Security.Roles;
@inject SchoolContext schoolContext
@inject UserManager<SzkolaXXII.Web.Areas.Identity.Data.User> UserManager

@{
    var user = await UserManager.GetUserAsync(User);
    var privileges = await UserManager.IsInRoleAsync(user, SystemDefaultRoles.Moderator) ||
                     await UserManager.IsInRoleAsync(user, SystemDefaultRoles.Administrator);

    var schools = new SelectList(schoolContext.Namespace, "Id", "Name");
}
<h1>Utwórz nowy przedmiot</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <input asp-for="SchoolId" type="hidden" />
            <table class="table table-borderless table-responsive-md">
                <thead>
                    <tr>
                        @if (privileges)
                        {
                            <th></th>
                        }
                        <th></th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @if (privileges)
                    {
                        <tr>
                            <td>Szkoła</td>
                            <td><select asp-for="SchoolId" class="form-control" asp-items="schools"></select></td>
                        </tr>
                    }
                        <tr>
                            <td>Nazwa</td>
                            <td><input asp-for="Name" class="form-control" /></td>
                        </tr>
                    <tr>
                        <td>Opis</td>
                        <td><input asp-for="Description" class="form-control" /></td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <button type="submit" class="btn btn-primary">Dodaj</button>
                            <a class="ml-2" asp-action="Index">Powrót do listy</a>
                        </td>
                    </tr>
                </tbody>
            </table>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SzkolaXXII/SzkolaXXII/Views/Subjects/CreateAssignment.cshtml
@model SzkolaXXII.Web.InputModel.AssignmentInputModel
@{
    ViewData["Title"] = "Dodaj zadanie";
}
@using SzkolaXXII.Web.Data;
@inject SchoolContext schoolContext

<h1>Dodaj zadanie</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateAssignment">
            <table class="table table-borderless table-responsive-md">
                <thead>
                    <tr>
                        <th></th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <input asp-for="SubjectId" type="hidden" value="@ViewBag.SubId" />
                        <td>Tytuł</td>
                        <td><input asp-for="Title" class="form-control" /></td>
                    </tr>
                    <tr>
                        <td>Opis</td>
                        <td><input asp-for="Description" class="form-control" /></td>
                    </tr>
                    <tr>
                        <td>Typ</td>
                        <td><input asp-for="Type" class="form-control" /></td>
                    </tr>
                    <tr>
                        <td>Waga</td>
                        <td><input asp-for="Weight" class="form-control" /></td>
                    </tr>
                    <tr>
                        <td>Data</td>
                        <td>
                            <input class="form-control" asp-for="Date" />
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <button type="submit" class="btn btn-primary">Dodaj</button>
                            <a class="ml-2" asp-action="Index">Powrót</a>
                        </td>
                    </tr>
                </tbody>
            </table>
        </form>
    </div>
</div>

SzkolaXXII/SzkolaXXII/Views/Subjects/Delete.cshtml
@model SzkolaXXII.Web.Models.School.Subject

@{
    ViewData["Title"] = "Usuń przedmiot";
}

<h1>Usuń przedmiot</h1>

<h3>Jesteś pewien, że chcesz usunąć ten przedmiot?</h3>
<div>
    <h4>Subject</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Nazwa
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            Opis
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Usuń" class="btn btn-danger" /> |
        <a asp-action="Index">Powrót do listy</a>
    </form>
</div>

SzkolaXXII/SzkolaXXII/Views/Subjects/Details.cshtml
@model SzkolaXXII.Web.Models.School.Subject

@{
	ViewData["Title"] = "Szczegóły";
}
@using SzkolaXXII.Web.Data;
@inject SchoolContext schoolContext

<h1>Szczegóły</h1>

<div>
	<hr />
	<dl class="row">
		<dt class="col-sm-2">
			Nazwa
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Name)
		</dd>
		<dt class="col-sm-2">
			Opis
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Description)
		</dd>
		<dt class="col-sm-2">
			Szkoła
		</dt>
		<dd class="col-sm-10">
			@schoolContext.Namespace.ToList().FirstOrDefault(x => x.Name == Model.School.Name).Name
		</dd>
	</dl>
</div>
<div>
	<a asp-action="Class" asp-route-id="@Model.Id">Pokaż Klasy</a> |
	<a asp-action="Edit" asp-route-id="@Model.Id">Edytuj</a> |
	<a asp-action="Index">Powrót do listy</a>
</div>

SzkolaXXII/SzkolaXXII/Views/Subjects/Edit.cshtml
@model SzkolaXXII.Web.Models.School.Subject

@{
    ViewData["Title"] = "Edytuj";
}

<h1>Edytuj</h1>

<h4>Przemiot</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Zapisz" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Powrót do listy</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SzkolaXXII/SzkolaXXII/Views/Subjects/Index.cshtml
@model IEnumerable<SzkolaXXII.Web.Models.School.Subject>
@{
	ViewData["Title"] = "Lista przemiotów";
}
@using SzkolaXXII.Web.Data;
@inject SchoolContext schoolContext

<h1>Lista przedmiotów</h1>

<p>
	<a asp-action="Create">Dodaj nowy</a>
</p>
<table class="table">
	<thead>
		<tr>
			<th>Nazwa przedmiotu</th>
			<th>Opis</th>
			<th>Szkoła</th>
			<th></th>
		</tr>
	</thead>
	<tbody>

		@foreach (var subject in Model)
		{

			<tr>
				<td>@subject.Name</td>
				<td>@subject.Description</td>
				<td>@schoolContext.Namespace.FirstOrDefault(n=>n.Id==subject.SchoolId).Name</td>
				<td>
					<a asp-action="Class" asp-route-id="@subject.Id">Lista Studentów</a> |
					<a asp-action="Edit" asp-route-id="@subject.Id">Edytuj</a> |
					<a asp-action="Details" asp-route-id="@subject.Id">Szczegóły</a> |
					<a asp-action="Delete" asp-route-id="@subject.Id">Usuń przedmiot</a> |
					<a asp-action="Subject" asp-route-id="@subject.Id">Strona Przedmiotu</a>
				</td>
			</tr>
		}
	</tbody>
</table>

SzkolaXXII/SzkolaXXII/Views/Subjects/SetStudentGrades.cshtml
@model IEnumerable<SzkolaXXII.Web.ViewModel.SetStudentGradeViewModel>

@{
    ViewData["Title"] = "SetStudentGrades";
}

<h1>Wystaw Ocenę</h1>


<table class="table">
    <thead>
        <tr>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <table class="table table-borderless table-responsive-md">
            <thead>
                <tr>
                    <th>Student</th>
                    <th>Ocena</th>
                    <th>Opcje</th>
                </tr>
            </thead>
       </table>
            @foreach (var item in Model)
            {
                <form asp-action="AddNewGradeForStudent">
                    <table class="table table-borderless table-responsive-md">
                        <tbody>
                            <tr>
                                <td>@item.User.UserName</td>
                                <td><input type="text" id="newGrade" name="NewGrade" value="@item.SubjectGrade.Grade"/></td>
                                <input type="hidden" id="newGrade" name="AssignmentId" value="@ViewBag.AssignmentId" />
                                <input type="hidden" id="newGrade" name="UserId" value="@item.User.Id" />
                                <td><button type="submit" class="btn btn-primary">Aktualizuj</button></td>
                            </tr>
                        </tbody>
                    </table>
                </form>
            }
    </tbody>
</table>

SzkolaXXII/SzkolaXXII/Views/Subjects/StudentGrades.cshtml
@model IEnumerable<SzkolaXXII.Web.ViewModel.StudentGradesViewModel>

@{
    ViewData["Title"] = "Twoje oceny";
}

<h1>Twoje oceny</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.AssignmentName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AssignmentType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Grade)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.AssignmentName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AssignmentType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Grade)
            </td>
        </tr>
}
    </tbody>
</table>

SzkolaXXII/SzkolaXXII/Views/Subjects/StudentSubject.cshtml
@model List<SzkolaXXII.Web.Models.School.Subject>
@{
    ViewData["Title"] = "StudentSubject";
}

@if (ViewBag.SubjectCount > 0)
{   
    <div class="table">
        @for (int i = 0; i < Model.Count; i += 2)
        {
            <div class="row">
                <div class="col">
                    <div class="card mb-3" style="width: 450px;">
                        <div class="row no-gutters">
                            <div class="col-md-4">
                                <svg class="bd-placeholder-img" width="100%" height="250" xmlns="https://unsplash.com/photos/OyCl7Y4y0Bk" aria-label="Placeholder: Image" preserveAspectRatio="xMidYMid slice" role="img"><title>Placeholder</title><rect width="100%" height="100%" fill="#868e96" /><text x="50%" y="50%" fill="#dee2e6" dy=".3em">Image</text></svg>

                            </div>
                            <div class="col-md-8">
                                <div class="card-body">
                                    <h5 class="card-title"><a asp-action="Subject" asp-route-id="@Model[i].Id">@Model[i].Name</a></h5>
                                    <p class="card-text">@Model[i].Description</p>
                                    <p class="card-text"><small class="text-muted">@Model[i].SubjectTeacher.</small></p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                @if (i + 1 < Model.Count)
                {
                    <div class="col">
                        <div class="card mb-3" style="max-width: 540px;">
                            <div class="row no-gutters">
                                <div class="col-md-4">
                                    <svg class="bd-placeholder-img" width="100%" height="250" xmlns="https://unsplash.com/photos/OyCl7Y4y0Bk" aria-label="Placeholder: Image" preserveAspectRatio="xMidYMid slice" role="img"><title>Placeholder</title><rect width="100%" height="100%" fill="#868e96" /><text x="50%" y="50%" fill="#dee2e6" dy=".3em">Image</text></svg>

                                </div>
                                <div class="col-md-8">
                                    <div class="card-body">
                                        <h5 class="card-title"><a asp-action="Subject" asp-route-id="@Model[i + 1].Id">@Model[i + 1].Name</a></h5>
                                        <p class="card-text">@Model[i + 1].Description</p>
                                        <p class="card-text"><small class="text-muted">@Model[i + 1].SubjectTeacher.</small></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        }
    </div>
}
else
{
    <div>
        Brak przedmiotów to wyświetlenia<br />
        Skontaktuj się z Administratorem
    </div>
}

SzkolaXXII/SzkolaXXII/Views/Subjects/Subject.cshtml
@model SzkolaXXII.Web.ViewModel.SubjectShowViewModel

@{
    ViewData["Title"] = "Subject";
}
@using Microsoft.AspNetCore.Identity
@using SzkolaXXII.Common.Security.Roles
@inject SignInManager<SzkolaXXII.Web.Areas.Identity.Data.User> SignInManager
@inject UserManager<SzkolaXXII.Web.Areas.Identity.Data.User> UserManager
@inject RoleManager<IdentityRole> RoleManager

<h1>@Model.Subject.Name</h1>
<h4>@Model.Subject.SubjectTeacher</h4>

@if (SignInManager.IsSignedIn(User))
{
    var user = await UserManager.GetUserAsync(User);
    var roles = await UserManager.GetRolesAsync(user);

    @if (roles.Contains(SystemDefaultRoles.Teacher) || roles.Contains(SystemDefaultRoles.Administrator))
    {
<div>
    <a asp-action="CreateAssignment" asp-route-id="@Model.Subject.Id">Dodaj zadanie</a> |
    <a asp-action="AddClass" asp-route-id="@Model.Subject.Id">Dodaj nową klase do przedmiotu</a>
</div>
    }
    else if (roles.Contains(SystemDefaultRoles.Student))
    {
        <a asp-action="StudentGrades" asp-route-subjectId="@Model.Subject.Id">Twoje oceny</a>
    }
}


<div>
    <hr />
    <dl class="row">
    </dl>

    @if (Model.Assignments.Count == 0)
    {<div>Nie ma żadnych zadań :(</div>}

    @foreach (var mod in Model.Assignments)
    {

        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">@mod.Title</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th>@mod.Description</th>
                </tr>
                <tr>
                    <th>  @mod.Type  |  @mod.Date</th>
                  
                </tr>
                <tr>

                    @if (SignInManager.IsSignedIn(User))
                    {
                        var user = await UserManager.GetUserAsync(User);
                        var roles = await UserManager.GetRolesAsync(user);

                        @if (roles.Contains(SystemDefaultRoles.Teacher) || roles.Contains(SystemDefaultRoles.Administrator))
                        {
                            <th scope="row"><a asp-action="SetStudentGrades" asp-route-subjectId="@Model.Subject.Id" asp-route-assignmentId="@mod.Id">Wystaw Ocene</a></th>
                        }

                    }

                </tr>
            </tbody>
        </table>
        <br />


    }

</div>