SzkolaXXII/SzkolaXXII/Models/School/Notes.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using SzkolaXXII.Web.Areas.Identity.Data;

namespace SzkolaXXII.Web.Models.School
{
    public class Notes
    {
        [Key]
        public string Id { get; set; }

        public string TeacherId { get; set; }
        public User Teacher { get; set; }

        public string StudentId { get; set; }
        public User Student { get; set; }

        public DateTime Time { get; set; }
        public bool Read { get; set; }

        [MaxLength(100)]
        public string Title { get; set; }

        [MaxLength(250)]
        public string Text { get; set; }
    }
}

SzkolaXXII/SzkolaXXII/Models/School/Subject.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SzkolaXXII.Web.Models.School
{
    public class Subject
    {
        [Key]
        public string Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string SchoolId { get; set; }
        public string TeacherId { get; set; }
        public Namespace School { get; set; }
        public ICollection<Assignment> Assignments { get; set; }
        public ICollection<SubjectTeacher> SubjectTeacher { get; set; }
        public ICollection<SubjectSchoolClass> SubjectSchoolClass { get; set; }
    }
}

SzkolaXXII/SzkolaXXII/Models/School/Timetable.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SzkolaXXII.Web.Models.School
{
    public class Timetable
    {
        [Key]
        public string Id { get; set; }
        public string DayofWeek { get; set; }
        public DateTime StartTime { get; set; }
        public DateTime EndTime { get; set; }
        public string Classroom { get; set; }

        public string SchoolClassId { get; set; }
        public SchoolClass SchoolClass { get; set; }

        public string SubjectId { get; set; }
        public Subject Subject { get; set; }
    }
}

SzkolaXXII/SzkolaXXII/Controllers/NotesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using SzkolaXXII.Common.Security.Roles;
using SzkolaXXII.Web.Areas.Identity.Data;
using SzkolaXXII.Web.Data;
using SzkolaXXII.Web.Models.School;
using SzkolaXXII.Web.Policies;
using SzkolaXXII.Web.ViewModel;

namespace SzkolaXXII.Web.Controllers
{
    public class NotesController : Controller
    {
        private readonly SchoolContext _schoolContext;
        private readonly UserManager<User> _userManager;

        public NotesController(SchoolContext schoolContext, UserManager<User> userManager)
        {
            _schoolContext = schoolContext;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            var userId = _userManager.GetUserId(User);
            var notes = _schoolContext.Notes.Where(x => x.StudentId == userId);

            List<NotesViewModel> list = new List<NotesViewModel>();

            foreach (var item in notes)
            {
                list.Add(new NotesViewModel
                {
                    Notes = item,
                    User = _schoolContext.Users.FirstOrDefault(x => x.Id == item.TeacherId),
                    Color = item.Read ? "#C6C6C6" : "#FFFFF0"
                });
            }

            if (list.Count > 1) list.OrderBy(x => x.Notes.Time);

            return View(list);
        }

        public async Task<IActionResult> ShowNotes(string id)
        {
            var notes = _schoolContext.Notes.FirstOrDefault(x => x.Id == id);

            if (!notes.Read)
            {
                notes.Read = true;
                _schoolContext.Notes.Update(notes);

                await _schoolContext.SaveChangesAsync();
            }

            NotesViewModel notesViewModel = new NotesViewModel()
            {
                Notes = notes,
                User = _schoolContext.Users.FirstOrDefault(x => x.Id == notes.TeacherId),
            };

            return View(notesViewModel);
        }
    }
}

SzkolaXXII/SzkolaXXII/Controllers/TeacherPanelController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using SzkolaXXII.Common.Const;
using SzkolaXXII.Common.Security.Roles;
using SzkolaXXII.Web.Areas.Identity.Data;
using SzkolaXXII.Web.Data;
using SzkolaXXII.Web.InputModel;
using SzkolaXXII.Web.Models.School;
using SzkolaXXII.Web.Policies;
using SzkolaXXII.Web.ViewModel;

namespace SzkolaXXII.Web.Controllers
{
    [Authorize(Roles = SystemDefaultRoles.Teacher)]
    public class TeacherPanelController : Controller
    {
        private readonly SchoolContext _context;
        private readonly UserManager<User> _userManager;

        public TeacherPanelController(SchoolContext context, UserManager<User> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            var userId = _userManager.GetUserId(User);

            if (userId == null)
            {
                return NotFound();
            }

            var schoolTeacher = _context.SchoolTeacher.FirstOrDefault(x => x.TeacherId == userId);

            if (schoolTeacher == null)
            {
                return NotFound();
            }

            return View();
        }

        public IActionResult Subjects()
        {
            var userId = _userManager.GetUserId(User);

            if (userId == null)
            {
                return NotFound();
            }

            var schoolTeacher = _context.SchoolTeacher.FirstOrDefault(x => x.TeacherId == userId);

            if (schoolTeacher == null)
            {
                return NotFound();
            }

            var subjectTeacher = _context.SubjectTeacher.FirstOrDefault(x => x.SchoolTeacher.Id == schoolTeacher.Id);

            if (subjectTeacher == null)
            {
                return View(null);
            }

            var subjects = _context.Subject.Where(x => _context.SubjectTeacher.Any(y => y.SchoolTeacherId == schoolTeacher.Id && x.Id == y.SubjectId));

            return View(subjects);
        }

        public IActionResult AddClass(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var subject = _context.Subject.FirstOrDefault(x => x.Id == id);

            if (subject == null)
            {
                return NotFound();
            }

            var schoolClass = _context.SchoolClass.Where(x => x.SchoolId == subject.SchoolId).ToList();

            if (schoolClass == null)
            {
                return NotFound();
            }

            var assignSchoolClass = _context.SchoolClass.ToList().Where(x => _context.SubjectSchoolClass.Any(y => y.SchoolClass == x && y.Subject.Id == id && x.SchoolId == subject.SchoolId));

            if (assignSchoolClass == null)
            {
                return View(new AddClassInputModel
                {
                    Id = id,
                    List = schoolClass
                });
            }

            schoolClass = schoolClass.Except(assignSchoolClass).ToList();

            if (schoolClass == null)
            {
                return NotFound();
            }

            return base.View(new AddClassInputModel
            {
                Id = id,
                List = schoolClass.ToList()
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddClass(AddClassInputModel model)
        {
            var schoolClass = _context.SchoolClass.FirstOrDefault(x => model.ClassId == x.Id);
            var subject = _context.Subject.FirstOrDefault(x => model.Id == x.Id);

            _context.SubjectSchoolClass.Add(new SubjectSchoolClass
            {
                Id = Guid.NewGuid().ToString(),
                SchoolClass = schoolClass,
                Subject = subject
            });

            await _context.SaveChangesAsync();

            return Redirect("~/TeacherPanel/Class/" + model.Id);
        }

        public async Task<IActionResult> Subject(string id)
        {
            var subject = _context.Subject.FirstOrDefault(n => n.Id == id);
            if (subject == null)
            {
                return NotFound();
            }

            var vievModel = new SubjectShowViewModel() { Assignments = null, Subject = subject };

            return View(vievModel);
        }

        [Authorize(Policy = AuthorizationPolicies.Name.AtLeastTeacher)]
        public async Task<IActionResult> Create(string schoolId)
        {
            var user = await _userManager.GetUserAsync(User);
            var roles = await _userManager.GetRolesAsync(user);

            if (schoolId == null && (!roles.Contains(SystemDefaultRoles.Administrator) &&
                !roles.Contains(SystemDefaultRoles.Moderator)))
            {
                var userId = _userManager.GetUserId(User);
                var schoolTeacher = _context.SchoolTeacher.FirstOrDefault(x => x.TeacherId == userId);

                if (schoolTeacher == null)
                {
                    return View("Error");
                }

                var school = _context.Namespace.FirstOrDefault(x => x.Id == schoolTeacher.SchoolId);

                if (school == null)
                {
                    return View("Error");
                }

                schoolId = schoolTeacher.SchoolId;
            }

            var viewModel = new SubjectViewModel
            {
                SchoolId = schoolId,
                Subjects = await _context.Subject.ToListAsync(),
            };

            return View(new SubjectInputModel { ViewModel = viewModel, SchoolId = schoolId });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(SubjectInputModel model)
        {
            if (ModelState.IsValid)
            {
                var school = _context.Namespace.FirstOrDefault(x => x.Id == model.SchoolId);

                var subject = new Subject()
                {
                    Id = Guid.NewGuid().ToString(),
                    Name = model.Name,
                    Description = model.Description,
                    School = school
                };

                _context.Add(subject);
                await _context.SaveChangesAsync();

                var user = await _userManager.GetUserAsync(User);
                var schoolTeacher = _context.SchoolTeacher.FirstOrDefault(x => x.TeacherId == user.Id);

                if (schoolTeacher == null)
                {
                    return RedirectToAction(nameof(Index));
                }

                var subjectTeacher = new SubjectTeacher()
                {
                    Id = Guid.NewGuid().ToString(),
                    SchoolTeacher = schoolTeacher,
                    Subject = subject
                };

                _context.Add(subjectTeacher);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Subjects));
            }

            return NotFound();
        }

        public async Task<IActionResult> OneSubject(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var subject = await _context.Subject.FindAsync(id);
            if (subject == null)
            {
                return NotFound();
            }

            var subjectSchoolClasses = _context.SubjectSchoolClass
                .Where(x => x.SubjectId == id)
                .Select(x => x.SchoolClassId);

            var schoolClasses = _context.SchoolClass
                .Where(x =>
                    subjectSchoolClasses
                        .Any(y => y == x.Id));

            var events = _context.ClassCalendarEvent.Where(x => schoolClasses.Any(y => y.Id == x.ClassId));
            var assignments = _context.Assigment.Where(x => x.SubjectId == id);

            OneSubjectViewModel oneSubjectView = new OneSubjectViewModel
            {
                Id = id,
                Name = subject.Name,
                Classes = schoolClasses,
                Events = events,
                Assignments = assignments
            };

            return View(oneSubjectView);
        }

        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var subject = await _context.Subject.FindAsync(id);
            if (subject == null)
            {
                return NotFound();
            }

            SubjectInputModel subjectInputModel = new SubjectInputModel
            {
                Id = subject.Id,
                Name = subject.Name,
                Description = subject.Description
            };

            return View(subjectInputModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,Name,Description")] Subject subject)
        {
            if (id != subject.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(subject);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SubjectExists(subject.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return Redirect("~/TeacherPanel/OneSubject/" + subject.Id);
            }

            return View(subject);
        }

SzkolaXXII/SzkolaXXII/Views/TeacherPanel/AddClass.cshtml
@model SzkolaXXII.Web.InputModel.AddClassInputModel
@{
    ViewData["Title"] = "AddClass";
    ViewData["Id"] = Model.Id;
    Layout = "~/Views/Shared/_PanelLayout.cshtml";
}
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/light-bootstrap-dashboard.css" />
    <!--     Fonts and icons     -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />
</head>
<body>
    <div class="wrapper">
        <div class="sidebar" data-color="black">
            <div class="sidebar-wrapper">
                <partial name="_TeacherOneSubjectPartial" />
            </div>
        </div>
        <div class="main-panel">
            <partial name="_AdminMenuHeader" />
            <div class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="card">
                                <div class="card-header">
                                    <h4 class="card-title">Dodaj klasę</h4>
                                </div>
                                <div class="card-body">
                                    <form asp-action="AddClass">
                                        <input asp-for="Id" type="hidden" />
                                        <div class="form-group">
                                            @if (Model.List.Count > 0)
                                            {
                                                <div class="row">
                                                    <label>Klasa</label>
                                                    <select class="form-control" asp-for="ClassId" asp-items="@Model.List.Select(x => new SelectListItem(x.Name, x.Id))"></select>
                                                </div>
                                                <button type="submit" class="btn btn-info pull-right">Dodaj</button>
                                                <a class="ml-2" asp-action="Class" asp-route-id="@Model.Id">Powrót do listy</a>
                                            }
                                            else
                                            {
                                                <div class="row">
                                                    <a class="ml-2">Brak klas do dodania</a>
                                                </div>
                                                <a class="ml-2" asp-action="Class" asp-route-id="@Model.Id">Powrót do listy</a>
                                            }
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

SzkolaXXII/SzkolaXXII/Views/TeacherPanel/AddNotes.cshtml
@model SzkolaXXII.Web.InputModel.AddNotesInputModel
@{
    ViewData["Title"] = "Dodaj uwagę";
    Layout = "~/Views/Shared/_PanelLayout.cshtml";
}
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/light-bootstrap-dashboard.css" />
    <!--     Fonts and icons     -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />
</head>
<body>
    <div class="wrapper">
        <div class="sidebar" data-color="black">
            <div class="sidebar-wrapper">
                <partial name="_TeacherMenuPartial" />
            </div>
        </div>
        <div class="main-panel">
            <partial name="_AdminMenuHeader" />
            <div class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="card">
                                <div class="card-header">
                                    <h4 class="card-title">Dodaj uwagę</h4>
                                </div>
                                <div class="card-body">
                                    <form asp-action="AddNotes">
                                        <input asp-for="StudentId" type="hidden" />
                                        <div class="form-group">
                                            <label class="control-label">Tytuł</label>
                                            <input asp-for="Title" class="form-control" />
                                            <span asp-validation-for="Title" class="text-danger"></span>
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label">Treść</label>
                                            <textarea asp-for="Text" rows="4" cols="80" class="form-control" placeholder="Opis..."></textarea>
                                        </div>
                                        <button type="submit" class="btn btn-info btn-fill pull-right">Dodaj</button>
                                        <a class="ml-2" asp-action="Notes">Powrót</a>
                                        <div class="clearfix"></div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SzkolaXXII/SzkolaXXII/Views/TeacherPanel/Calendar.cshtml
@model SzkolaXXII.Web.ViewModel.TeacherCalendarEventViewModel

@{
    ViewData["Title"] = "Kalendarz";
    ViewData["Id"] = Model.SubjectId;
    Layout = "~/Views/Shared/_PanelLayout.cshtml";
}
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>SzkolaXXII - Panel administratora - @ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/light-bootstrap-dashboard.css" />
    <!--     Fonts and icons     -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />
</head>
<body>
    <div class="wrapper">
        <div class="sidebar" data-color="black">
            <div class="sidebar-wrapper">
                <partial name="_TeacherOneSubjectPartial" />
            </div>
        </div>
        <div class="main-panel">
            <partial name="_AdminMenuHeader" />
            <div class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="card strpied-tabled-with-hover">
                                @if (Model.SchoolClasses != null && Model.SchoolClasses.Count > 0)
                                {<div class="container my-2">
                                        <br />
                                        <table class="col-md-3">
                                            <tr>
                                                <td>
                                                    <div class="btn-group">
                                                        <button type="button" class="btn btn-info btn-fill dropdown-toggle" data-toggle="dropdown">
                                                            @Model.Name <span class="caret"></span>
                                                        </button>
                                                        <ul class="dropdown-menu" role="menu">
                                                            @foreach (var item in Model.SchoolClasses)
                                                            {
                                                                <li><a class="btn btn-info btn-fill btn-lg btn-block btn btn-outline-primary" asp-action="Calendar" asp-route-id="@item.Id" asp-route-subjectId="@Model.SubjectId">@item.Name</a></li>
                                                            }
                                                        </ul>
                                                    </div>
                                                </td>
                                                <td><a class="btn btn-info btn-fill float-left" asp-action="CreateClassEvent" asp-route-id="@Model.Id" asp-route-subjectId="@Model.SubjectId">Dodaj Wydarzenie</a></td>
                                            </tr>
                                        </table>
                                        <div class="row">
                                            <div class="col-md-1">
                                                <br />
                                                <br />
                                                <br />
                                                <br />
                                                <br />
                                                <br />
                                                <br />
                                                <br />
                                                <br />
                                                <br />
                                                <br />
                                                <br />
                                                <br />
                                                <a class="material-icons col-md-2" style="color:dimgrey;" href="@Url.Action("Prev", "TeacherPanel", new { month = Model.CalendarEventViewModel.Month, year = Model.CalendarEventViewModel.Year, id = Model.Id, subjectId = Model.SubjectId})">keyboard_arrow_left</a>
                                            </div>
                                            <div class="col-md-10">
                                                @*
                                                *@
                                                <calendar month="@Model.CalendarEventViewModel.Month" year="@Model.CalendarEventViewModel.Year" events="@Model.CalendarEventViewModel.Events" />
                                            </div>
                                            <div class="col-md-1">
                                                <br />
                                                <br />
                                                <br />
                                                <br />
                                                <br />
                                                <br />
                                                <br />
                                                <br />
                                                <br />
                                                <br />
                                                <br />
                                                <br />
                                                <br />
                                                <a class="material-icons pull-right" style="color:dimgrey;" href="@Url.Action("Next", "TeacherPanel", new { month = Model.CalendarEventViewModel.Month, year = Model.CalendarEventViewModel.Year, id = Model.Id, subjectId = Model.SubjectId})">keyboard_arrow_right</a>
                                            </div>
                                        </div>
                                    </div>
                                }
                                else
                                {
                                    <span>Na razie nie masz klasy.</span>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

SzkolaXXII/SzkolaXXII/Views/TeacherPanel/Class.cshtml
@model SzkolaXXII.Web.ViewModel.SubjectSchoolClassViewModel

@{
    ViewData["Title"] = "Klasy";
    ViewData["Id"] = Model.Id;
    Layout = "~/Views/Shared/_PanelLayout.cshtml";
}
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>SzkolaXXII - Panel administratora - @ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/light-bootstrap-dashboard.css" />
    <!--     Fonts and icons     -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />
</head>
<body>
    <div class="wrapper">
        <div class="sidebar" data-color="black">
            <div class="sidebar-wrapper">
                <partial name="_TeacherOneSubjectPartial" />
            </div>
        </div>
        <div class="main-panel">
            <partial name="_AdminMenuHeader" />
            <div class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="card strpied-tabled-with-hover">
                                <div class="card-header ">
                                    <a class="btn btn-info btn-fill pull-right" asp-action="AddClass" asp-route-id="@Model.Id">Dodaj nową klase do przedmiotu</a>
                                    <h4 class="card-title">Lista klas</h4>
                                </div>
                                <div class="card-body table-full-width table-responsive">
                                    <table class="table table-hover table-striped">
                                        <thead>
                                        <th>Nazwa</th>
                                        <th>Akcja</th>
                                        </thead>
                                        <tbody>
                                            @if (Model != null)
                                                @foreach (var item in Model.List)
                                                {
                                                    <tr>
                                                        <td>
                                                            @Html.DisplayFor(modelItem => item.Name)
                                                        </td>
                                                        <td>
                                                            <a class="material-icons" style="color:dimgrey;" asp-controller="SchoolClasses" asp-action="ShowStudents" asp-route-id="@item.Id" title="Lista uczniów">list_alt</a>
                                                            <a class="material-icons" style="color:darkred; margin-left:15px" asp-action="Remove" asp-route-SubjectId="@Model.Id" asp-route-ClassId="@item.Id" title="Usuń klase">clear</a>
                                                        </td>
                                                    </tr>
                                                }
                                        </tbody>
                                    </table>
                                    <div>
                                        <a class="col-md-2" asp-action="OneSubject" asp-route-id="@Model.Id">Powrót</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

SzkolaXXII/SzkolaXXII/Views/TeacherPanel/ShowStudents.cshtml
@model List<SzkolaXXII.Web.ViewModel.SchoolStudentIndexViewModel>

@{
    ViewData["Title"] = "Klasa";
    ViewData["Id"] = ViewBag.SubjectId;
    Layout = "_TeacherOneSubjectLayout";
}

<h1>Klasa @ViewBag.ClassName</h1>
<h3>Wychowawca: @ViewBag.EducatorName</h3>
<br />
<table class="table table-hover">
    <thead class="thead-light">
        <tr>
            <th style="width:80%">
                Nazwa studenta
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if (Model != null && Model.Count >= 0)
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @item.Student.UserName
                    </td>
                    <td>
                        <a class="btn btn-outline-primary float-right" asp-action="AddNotes" asp-route-id="@item.Student.Id">Dodaj uwagę</a>
                    </td>
                </tr>
            }
    </tbody>
</table>