SzkolaXXII/SzkolaXXII/Controllers/NamespacesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Threading.Tasks;
using SzkolaXXII.Web.Data;
using SzkolaXXII.Web.Models.School;

namespace SzkolaXXII.Web.Controllers
{
    public class NamespacesController : Controller
    {
        private readonly SchoolContext _context;

        public NamespacesController(SchoolContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.Namespace.ToListAsync());
        }

        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @namespace = await _context.Namespace
                .FirstOrDefaultAsync(m => m.Id == id);
            if (@namespace == null)
            {
                return NotFound();
            }

            return View(@namespace);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Address,Name")] Namespace @namespace)
        {
            if (ModelState.IsValid)
            {
                @namespace.Id = Guid.NewGuid().ToString();
                _context.Add(@namespace);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(@namespace);
        }

        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @namespace = await _context.Namespace.FindAsync(id);
            if (@namespace == null)
            {
                return NotFound();
            }
            return View(@namespace);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,Address,Name")] Namespace @namespace)
        {
            if (id != @namespace.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(@namespace);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException ex)
                {
                    if (!NamespaceExists(@namespace.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw ex;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(@namespace);
        }

        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @namespace = await _context.Namespace
                .FirstOrDefaultAsync(m => m.Id == id);
            if (@namespace == null)
            {
                return NotFound();
            }

            return View(@namespace);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var @namespace = await _context.Namespace.FindAsync(id);

            _context.Namespace.Remove(@namespace);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        private bool NamespaceExists(string id)
        {
            return _context.Namespace.Any(e => e.Id == id);
        }
    }
}

SzkolaXXII/SzkolaXXII/Controllers/RoleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;
using SzkolaXXII.Common.Security.Roles;

namespace SzkolaXXII.Web.Controllers
{
    [Authorize(Roles = SystemDefaultRoles.Administrator)]
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;

        public RoleController(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
        }

        public IActionResult Index()
        {
            var roles = _roleManager.Roles.ToList();
            return View(roles);
        }

        public IActionResult Create()
        {
            return View(new IdentityRole());
        }

        [HttpPost]
        public async Task<IActionResult> Create(IdentityRole role)
        {
            await _roleManager.CreateAsync(role);
            return RedirectToAction("Index");
        }
    }
}

SzkolaXXII/SzkolaXXII/Controllers/SchoolTeachersController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Threading.Tasks;
using SzkolaXXII.Common.Security.Roles;
using SzkolaXXII.Web.Areas.Identity.Data;
using SzkolaXXII.Web.Data;
using SzkolaXXII.Web.InputModel;
using SzkolaXXII.Web.Models.School;
using SzkolaXXII.Web.ViewModel;

namespace SzkolaXXII.Web.Models
{
    public class SchoolTeachersController : Controller
    {
        private readonly SchoolContext _schoolContext;
        private readonly UserManager<User> _userManager;

        public SchoolTeachersController(SchoolContext schoolContext, UserManager<User> userManager)
        {
            _schoolContext = schoolContext;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(User);
            var roles = await _userManager.GetRolesAsync(user);


            if (roles.Contains(SystemDefaultRoles.Administrator))
            {
                ViewData["schoolCount"] = 2;
                ViewData["schools"] = _schoolContext.Namespace;
                var schoolTeachers = await _schoolContext.SchoolTeacher.ToListAsync();
                return View(schoolTeachers);
            }


            var schoolCount = _schoolContext.SchoolTeacher.Where(x => x.TeacherId == user.Id).Count();
            var schoolId = _schoolContext.SchoolTeacher.Where(x => x.TeacherId == user.Id).Select(x => x.SchoolId);
            ViewData["schoolCount"] = schoolCount;
            ViewData["schools"] = _schoolContext.Namespace.Where(x => schoolId.Contains(x.Id));
            var schoolContext = await _schoolContext.SchoolTeacher.Where(x => schoolId.Contains(x.SchoolId)).ToListAsync();

            return View(schoolContext);
        }

        public async Task<IActionResult> SchoolChosenIndex(string id)
        {
            ViewData["school"] = await _schoolContext.Namespace.FindAsync(id);
            var schoolContext = await _schoolContext.SchoolTeacher.Where(x => x.SchoolId == id).Include(x => x.Teacher).ToListAsync();

            return View(schoolContext);
        }

        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var schoolTeacher = await _schoolContext.SchoolTeacher
                .FirstOrDefaultAsync(m => m.Id == id);
            if (schoolTeacher == null)
            {
                return NotFound();
            }

            return View(schoolTeacher);
        }

        public async Task<IActionResult> Create()
        {
            var teachers = await _userManager.GetUsersInRoleAsync(SystemDefaultRoles.Teacher);

            var viewModel = new SchoolTeacherViewModel
            {
                Schools = await _schoolContext.Namespace.ToListAsync(),
                Users = teachers.ToList(),
                SchoolNames = _schoolContext.Namespace.Select(x => x.Name).ToList(),
                UserNames = teachers.Select(x => x.UserName).ToList(),
                SchoolTeachers = await _schoolContext.SchoolTeacher.ToListAsync()
            };

            return View(new SchoolTeacherInputModel { ViewModel = viewModel });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(SchoolTeacherInputModel model)
        {
            if (ModelState.IsValid)
            {
                var teacher = _userManager.Users.FirstOrDefault(x => x.UserName == model.Teacher);
                var school = _schoolContext.Namespace.FirstOrDefault(x => x.Name == model.School);
                var schoolTeachers = await _schoolContext.SchoolTeacher.ToListAsync();
                
                if (!_schoolContext.SchoolTeacher.Any(e => e.TeacherId == teacher.Id && e.SchoolId == school.Id))
                {
                    var schoolTeacher = new SchoolTeacher()
                    {
                        Id = Guid.NewGuid().ToString(),
                        TeacherId = teacher.Id,
                        School = school
                    };

                    _schoolContext.Add(schoolTeacher);
                    await _schoolContext.SaveChangesAsync();
                    return RedirectToAction("SchoolList", "Admin");
                }
            }
            return NotFound();
        }

        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var schoolTeacher = await _schoolContext.SchoolTeacher
                .FirstOrDefaultAsync(m => m.Id == id);
            if (schoolTeacher == null)
            {
                return NotFound();
            }

            return View(schoolTeacher);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var schoolTeacher = await _schoolContext.SchoolTeacher.FindAsync(id);
            _schoolContext.SchoolTeacher.Remove(schoolTeacher);
            await _schoolContext.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

    }
}

SzkolaXXII/SzkolaXXII/Views/Admin/AddUserRole.cshtml
@model SzkolaXXII.Web.InputModel.UserRoleInputModel
@{
    ViewData["Title"] = "Dodawanie roli użytkownika";
    Layout = "~/Views/Shared/_PanelLayout.cshtml";
}
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>SzkolaXXII - Panel administratora - @ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/light-bootstrap-dashboard.css" />
    <!--     Fonts and icons     -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />
</head>
<body>
    <div class="wrapper">
        <div class="sidebar" data-color="black">
            <div class="sidebar-wrapper">
                <partial name="_AdminMenuPartial" />
            </div>
        </div>
        <div class="main-panel">
            <partial name="_AdminMenuHeader" />
            <div class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-5">

                            <div class="card">
                                <div class="card-header">
                                    <h4 class="card-title">Dodawanie roli użytkownika</h4>
                                </div>
                                <div class="card-body">
                                    <form asp-action="AddUserRole">
                                        <input type="hidden" asp-for="ViewModel.Name" value="@Model.ViewModel.Name" />
                                        <input type="hidden" asp-for="ViewModel.Email" value="@Model.ViewModel.Email" />
                                        <input type="hidden" asp-for="ViewModel.UserId" value="@Model.ViewModel.UserId" />
                                        <div class="row">
                                            <div class="col-md-5 pr-1">
                                                <div class="form-group">
                                                    <label>Użytkownik</label>
                                                    <p>@Model.ViewModel.Name</p>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-5 pr-1">
                                                <div class="form-group">
                                                    <label>Email</label>
                                                    <p>@Model.ViewModel.Email</p>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-5 pr-1">
                                                <div class="form-group">
                                                    <label for="exampleInputEmail1">Szkoła</label>
                                                    <select class="form-control" asp-for="SchoolId" asp-items="@Model.ViewModel.Schools.Select(x => new SelectListItem(x.Key, x.Value))"></select>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-5 pr-1">
                                                <div class="form-group">
                                                    <label>Rola</label>
                                                    <select class="form-control" asp-for="Role" asp-items="@Model.ViewModel.Roles.Select(x => new SelectListItem(x, x))"></select>
                                                </div>
                                            </div>
                                        </div>

                                        <button type="submit" class="btn btn-info btn-fill pull-right">Dodaj</button>

                                        <a class="ml-2" asp-action="Roles">Powrót</a>
                                        <div class="clearfix"></div>
                                    </form>
                                </div>
                            </div>


                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

SzkolaXXII/SzkolaXXII/Views/Admin/DeleteUserRole.cshtml
@model SzkolaXXII.Web.InputModel.UserRoleInputModel

@{
    ViewData["Title"] = "Usuwanie roli użytkownika";
    Layout = "~/Views/Shared/_PanelLayout.cshtml";
}
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>SzkolaXXII - Panel administratora - @ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/light-bootstrap-dashboard.css" />
    <!--     Fonts and icons     -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />
</head>
<body>
    <div class="wrapper">
        <div class="sidebar" data-color="black">
            <div class="sidebar-wrapper">
                <partial name="_AdminMenuPartial" />
            </div>
        </div>
        <div class="main-panel">
            <partial name="_AdminMenuHeader" />
            <div class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-5">

                            <div class="card">
                                <div class="card-header">
                                    <h4 class="card-title">Usuwanie roli użytkownika</h4>
                                </div>
                                @if (!string.IsNullOrEmpty(ViewData["ErrorMessage"].ToString()))
                                {
                                    <p class="text-danger">@ViewData["ErrorMessage"].ToString()</p>
                                }
                                <div class="card-body">
                                    <form asp-action="DeleteUserRole">
                                        <input type="hidden" asp-for="ViewModel.Name" value="@Model.ViewModel.Name" />
                                        <input type="hidden" asp-for="ViewModel.Email" value="@Model.ViewModel.Email" />
                                        <input type="hidden" asp-for="ViewModel.UserId" value="@Model.ViewModel.UserId" />
                                        <div class="row">
                                            <div class="col-md-5 pr-1">
                                                <div class="form-group">
                                                    <label>Użytkownik</label>
                                                    <p>@Model.ViewModel.Name</p>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-5 pr-1">
                                                <div class="form-group">
                                                    <label>Email</label>
                                                    <p>@Model.ViewModel.Email</p>
                                                </div>
                                            </div>
                                        </div>
                                        @if (Model.ViewModel.Schools != null)
                                        {
                                            <div class="row">
                                                <div class="col-md-5 pr-1">
                                                    <div class="form-group">
                                                        <label for="exampleInputEmail1">Szkoła</label>
                                                        <p>
                                                            <input type="hidden" asp-for="@Model.SchoolId" />
                                                            @Model.ViewModel?.Schools?.FirstOrDefault(x => x.Value == Model.SchoolId).Key
                                                        </p>
                                                    </div>
                                                </div>
                                            </div>
                                        }
                                        <div class="row">
                                            <div class="col-md-5 pr-1">
                                                <div class="form-group">
                                                    <label>Rola</label>
                                                    <select class="form-control" asp-for="Role" asp-items="@Model.ViewModel.Roles.Select(x => new SelectListItem(x, x))"></select>
                                                </div>
                                            </div>
                                        </div>

                                        <button type="submit" class="btn btn-info btn-fill pull-right">Usuń</button>

                                        <a class="ml-2" asp-action="Roles">Powrót</a>
                                        <div class="clearfix"></div>
                                    </form>
                                </div>
                            </div>


                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

SzkolaXXII/SzkolaXXII/Views/Admin/Index.cshtml
@using SzkolaXXII.Web.ViewModel
@model AdminIndexViewModel
@{
    ViewData["Title"] = "Panel administratora";
    Layout = "~/Views/Shared/_PanelLayout.cshtml";
}
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>SzkolaXXII - Panel administratora - @ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/light-bootstrap-dashboard.css" />
    <!--     Fonts and icons     -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />
</head>
<body>
    <div class="wrapper">
        <div class="sidebar" data-color="black">
            <div class="sidebar-wrapper">
                <partial name="_AdminMenuPartial" />
            </div>
        </div>

        <div class="main-panel">
            <partial name="_AdminMenuHeader" />
        </div>

    </div>
</body>

SzkolaXXII/SzkolaXXII/Views/Admin/Roles.cshtml
@model List<SzkolaXXII.Web.ViewModel.AdminUserRolesViewModel>
@using Microsoft.AspNetCore.Identity

@inject UserManager<SzkolaXXII.Web.Areas.Identity.Data.User> userManager

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_PanelLayout.cshtml";
}
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>SzkolaXXII - Panel administratora - @ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/light-bootstrap-dashboard.css" />
    <!--     Fonts and icons     -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />
</head>
<body>
    <div class="wrapper">
        <div class="sidebar" data-color="black">
            <div class="sidebar-wrapper">
                <partial name="_AdminMenuPartial" />
            </div>
        </div>
        <div class="main-panel">
            <partial name="_AdminMenuHeader" />
            <div class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="card strpied-tabled-with-hover">
                                <div class="card-header ">
                                    <h4 class="card-title">Przegląd ról</h4>
                                    <p class="card-category">Panel Administratora</p>
                                </div>
                                <div class="card-body table-full-width table-responsive">
                                    <table class="table table-hover table-striped">
                                        <thead>
                                        <th>Użytkownik</th>
                                        <th>Emial</th>
                                        <th>Uprawnienia</th>
                                        <th>Akcja</th>
                                        </thead>
                                        <tbody>
                                            @foreach (var user in Model)
                                            {
                                                <tr>
                                                    <td>@user.Name</td>
                                                    <td>@user.Email</td>
                                                    <td>
                                                        @if (user.Roles.Any())
                                                        {
                                                            var roleString = string.Empty;
                                                            @foreach (var role in user.Roles)
                                                            {
                                                                roleString += $"{role} ";
                                                            }

                                                            <span>@roleString</span>
                                                        }
                                                        else
                                                        {
                                                            <span>Brak ról</span>
                                                        }
                                                    </td>
                                                    <td>
                                                        @if (user.UserId != userManager.GetUserId(User))
                                                        {
                                                            <a class="material-icons" style="color:darkolivegreen" asp-action="AddUserRole" asp-route-id="@user.UserId" title="Dodaj Role">add_circle</a>
                                                            @if (user.Roles.Any())
                                                            {
                                                                <a class="material-icons" style="color:darkred; margin-left:15px" asp-action="DeleteUserRole" asp-route-id="@user.UserId" title="Usuń Role">cancel</a>

                                                            }
                                                        }
                                                    </td>
                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

SzkolaXXII/SzkolaXXII/Views/Admin/SchoolList.cshtml
@model IEnumerable<SzkolaXXII.Web.Models.School.Namespace>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_PanelLayout.cshtml";
}
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>SzkolaXXII - Panel administratora - @ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/light-bootstrap-dashboard.css" />
    <!--     Fonts and icons     -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />
</head>
<body>
    <div class="wrapper">
        <div class="sidebar" data-color="black">
            <div class="sidebar-wrapper">
                <partial name="_AdminMenuPartial" />
            </div>
        </div>
        <div class="main-panel">
            <partial name="_AdminMenuHeader" />
            <div class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="card strpied-tabled-with-hover">
                                <div class="card-header ">
                                    <a class="btn btn-info btn-fill pull-right" asp-controller="Namespaces" asp-action="Create">Dodaj nową szkołę</a>
                                    <h4 class="card-title">Lista szkół</h4>
                                    <p class="card-category">Panel Admina</p>
                                </div>
                                <div class="card-body table-full-width table-responsive">
                                    <table class="table table-hover table-striped">
                                        <thead>
                                        <th>Adres</th>
                                        <th>Nazwa szkoły</th>
                                        <th>Akcja</th>
                                        </thead>
                                        <tbody>
                                            @foreach (var item in Model)
                                            {
                                                <tr>
                                                    <td>
                                                        @Html.DisplayFor(modelItem => item.Address)
                                                    </td>
                                                    <td>
                                                        @Html.DisplayFor(modelItem => item.Name)
                                                    </td>
                                                    <td>
                                                        <a class="material-icons" style="color:darkolivegreen" asp-controller="SchoolTeachers" asp-action="Create" title="Dodaj Nauczyciela">how_to_reg</a>
                                                        <a class="material-icons" style="color:dimgrey; margin-left:15px" asp-controller="Namespaces" asp-action="Edit" asp-route-id="@item.Id" title="Edytuj">edit</a>
                                                        <a class="material-icons" style="color:dimgrey; margin-left:15px" asp-controller="Namespaces" asp-action="Details" asp-route-id="@item.Id" title="Szczegóły">details</a>
                                                        <a class="material-icons" style="color:darkred; margin-left:15px" asp-controller="Namespaces" asp-action="Delete" asp-route-id="@item.Id" title="Usuń">cancel</a>
                                                    </td>
                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>